/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 자동완성 제안 데이터
 * @export
 * @interface AutoCompleteSuggestionsSuccessResponseData
 */
export interface AutoCompleteSuggestionsSuccessResponseData {
    /**
     * 검색 자동완성 제안 목록
     * @type {Array<string>}
     * @memberof AutoCompleteSuggestionsSuccessResponseData
     */
    'suggestions'?: Array<string>;
}
