/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface BannerImageSuccessResponseDataInner
 */
export interface BannerImageSuccessResponseDataInner {
    /**
     * 배너 ID
     * @type {number}
     * @memberof BannerImageSuccessResponseDataInner
     */
    'id'?: number;
    /**
     * 배너 이미지 URL
     * @type {string}
     * @memberof BannerImageSuccessResponseDataInner
     */
    'bannerUrl'?: string;
    /**
     * 클릭 시 이동할 URL
     * @type {string}
     * @memberof BannerImageSuccessResponseDataInner
     */
    'redirectUrl'?: string;
}
