/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrandListSuccessResponseDataContentInner } from './brand-list-success-response-data-content-inner';

/**
 * 
 * @export
 * @interface BrandListSuccessResponseData
 */
export interface BrandListSuccessResponseData {
    /**
     * 
     * @type {Array<BrandListSuccessResponseDataContentInner>}
     * @memberof BrandListSuccessResponseData
     */
    'content'?: Array<BrandListSuccessResponseDataContentInner>;
    /**
     * 
     * @type {number}
     * @memberof BrandListSuccessResponseData
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof BrandListSuccessResponseData
     */
    'totalElements'?: number;
}


