/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface BrandListSuccessResponseDataContentInner
 */
export interface BrandListSuccessResponseDataContentInner {
    /**
     * 
     * @type {number}
     * @memberof BrandListSuccessResponseDataContentInner
     */
    'brandId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BrandListSuccessResponseDataContentInner
     */
    'brandName'?: string;
    /**
     * 
     * @type {string}
     * @memberof BrandListSuccessResponseDataContentInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof BrandListSuccessResponseDataContentInner
     */
    'totalCampaigns'?: number;
    /**
     * 
     * @type {number}
     * @memberof BrandListSuccessResponseDataContentInner
     */
    'activeCampaigns'?: number;
}


