/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 캠페인 미션 가이드
 * @export
 * @interface CampaignMissionGuideResponseData
 */
export interface CampaignMissionGuideResponseData {
    /**
     * 캠페인 ID
     * @type {number}
     * @memberof CampaignMissionGuideResponseData
     */
    'campaignId'?: number;
    /**
     * 미션 가이드
     * @type {string}
     * @memberof CampaignMissionGuideResponseData
     */
    'missionGuide'?: string;
}


