/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignV1ListSuccessResponseDataCampaignsInner } from './campaign-v1-list-success-response-data-campaigns-inner';
import { CampaignV1ListSuccessResponseDataPagination } from './campaign-v1-list-success-response-data-pagination';

/**
 * 캠페인 목록 데이터
 * @export
 * @interface CampaignV1ListSuccessResponseData
 */
export interface CampaignV1ListSuccessResponseData {
    /**
     * 캠페인 목록
     * @type {Array<CampaignV1ListSuccessResponseDataCampaignsInner>}
     * @memberof CampaignV1ListSuccessResponseData
     */
    'campaigns'?: Array<CampaignV1ListSuccessResponseDataCampaignsInner>;
    /**
     * 
     * @type {CampaignV1ListSuccessResponseDataPagination}
     * @memberof CampaignV1ListSuccessResponseData
     */
    'pagination'?: CampaignV1ListSuccessResponseDataPagination;
}


