/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 신청 결과 데이터
 * @export
 * @interface CampaignApplicationSuccessResponseData
 */
export interface CampaignApplicationSuccessResponseData {
    /**
     * 신청 ID
     * @type {number}
     * @memberof CampaignApplicationSuccessResponseData
     */
    'applicationId'?: number;
    /**
     * 캠페인 ID
     * @type {number}
     * @memberof CampaignApplicationSuccessResponseData
     */
    'campaignId'?: number;
    /**
     * 신청 상태
     * @type {string}
     * @memberof CampaignApplicationSuccessResponseData
     */
    'status'?: string;
    /**
     * 신청 일시
     * @type {string}
     * @memberof CampaignApplicationSuccessResponseData
     */
    'appliedAt'?: string;
}



