/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CampaignV1ListSuccessResponseDataCampaignsInnerCategory
 */
export interface CampaignV1ListSuccessResponseDataCampaignsInnerCategory {
    /**
     * 카테고리 타입
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInnerCategory
     */
    'type'?: string;
    /**
     * 카테고리명
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInnerCategory
     */
    'name'?: string;
}
