/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 캠페인 상세 정보
 * @export
 * @interface CampaignDetailInfoResponseData
 */
export interface CampaignDetailInfoResponseData {
    /**
     * 캠페인 ID
     * @type {number}
     * @memberof CampaignDetailInfoResponseData
     */
    'campaignId'?: number;
    /**
     * 제품 간단 정보
     * @type {string}
     * @memberof CampaignDetailInfoResponseData
     */
    'productShortInfo'?: string;
    /**
     * 제품 상세 정보
     * @type {string}
     * @memberof CampaignDetailInfoResponseData
     */
    'productDetails'?: string;
    /**
     * 선정 기준
     * @type {string}
     * @memberof CampaignDetailInfoResponseData
     */
    'selectionCriteria'?: string;
    /**
     * 리뷰 마감일
     * @type {Date}
     * @memberof CampaignDetailInfoResponseData
     */
    'reviewDeadlineDate'?: Date;
    /**
     * 선정일
     * @type {Date}
     * @memberof CampaignDetailInfoResponseData
     */
    'selectionDate'?: Date;
    /**
     * 신청 마감일
     * @type {Date}
     * @memberof CampaignDetailInfoResponseData
     */
    'applicationDeadlineDate'?: Date;
}



