/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignApplicantsSuccessResponseDataApplicantsInnerUser } from './campaign-applicants-success-response-data-applicants-inner-user';

/**
 * 
 * @export
 * @interface CampaignApplicantsSuccessResponseDataApplicantsInner
 */
export interface CampaignApplicantsSuccessResponseDataApplicantsInner {
    /**
     * 
     * @type {number}
     * @memberof CampaignApplicantsSuccessResponseDataApplicantsInner
     */
    'applicationId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CampaignApplicantsSuccessResponseDataApplicantsInner
     */
    'applicationStatus'?: string;
    /**
     * 
     * @type {CampaignApplicantsSuccessResponseDataApplicantsInnerUser}
     * @memberof CampaignApplicantsSuccessResponseDataApplicantsInner
     */
    'user'?: CampaignApplicantsSuccessResponseDataApplicantsInnerUser;
}


