/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 페이징 정보
 * @export
 * @interface CampaignV1ListSuccessResponseDataPagination
 */
export interface CampaignV1ListSuccessResponseDataPagination {
    /**
     * 현재 페이지 번호
     * @type {number}
     * @memberof CampaignV1ListSuccessResponseDataPagination
     */
    'pageNumber'?: number;
    /**
     * 페이지 크기
     * @type {number}
     * @memberof CampaignV1ListSuccessResponseDataPagination
     */
    'pageSize'?: number;
    /**
     * 총 페이지 수
     * @type {number}
     * @memberof CampaignV1ListSuccessResponseDataPagination
     */
    'totalPages'?: number;
    /**
     * 총 요소 수
     * @type {number}
     * @memberof CampaignV1ListSuccessResponseDataPagination
     */
    'totalElements'?: number;
    /**
     * 첫 페이지 여부
     * @type {boolean}
     * @memberof CampaignV1ListSuccessResponseDataPagination
     */
    'first'?: boolean;
    /**
     * 마지막 페이지 여부
     * @type {boolean}
     * @memberof CampaignV1ListSuccessResponseDataPagination
     */
    'last'?: boolean;
}



