/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 캠페인 데이터
 * @export
 * @interface CampaignData
 */
export interface CampaignData {
    /**
     * 캠페인 ID
     * @type {number}
     * @memberof CampaignData
     */
    'id'?: number;
    /**
     * 캠페인 제목
     * @type {string}
     * @memberof CampaignData
     */
    'title'?: string;
    /**
     * 승인 상태
     * @type {string}
     * @memberof CampaignData
     */
    'approvalStatus'?: CampaignDataApprovalStatusEnum;
    /**
     * 생성일시
     * @type {string}
     * @memberof CampaignData
     */
    'createdAt'?: string;
}

/**
    * @export
    * @enum {string}
    */
export type CampaignDataApprovalStatusEnum = 
  'PENDING'|
  'APPROVED'|
  'REJECTED'



