/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 캠페인 기본 정보
 * @export
 * @interface CampaignBasicInfoResponseData
 */
export interface CampaignBasicInfoResponseData {
    /**
     * 캠페인 ID
     * @type {number}
     * @memberof CampaignBasicInfoResponseData
     */
    'campaignId'?: number;
    /**
     * 캠페인 타입
     * @type {string}
     * @memberof CampaignBasicInfoResponseData
     */
    'campaignType'?: string;
    /**
     * 카테고리 타입
     * @type {string}
     * @memberof CampaignBasicInfoResponseData
     */
    'categoryType'?: string;
    /**
     * 카테고리명
     * @type {string}
     * @memberof CampaignBasicInfoResponseData
     */
    'categoryName'?: string;
    /**
     * 캠페인 제목
     * @type {string}
     * @memberof CampaignBasicInfoResponseData
     */
    'title'?: string;
    /**
     * 최대 신청자 수
     * @type {number}
     * @memberof CampaignBasicInfoResponseData
     */
    'maxApplicants'?: number;
    /**
     * 현재 신청자 수
     * @type {number}
     * @memberof CampaignBasicInfoResponseData
     */
    'currentApplicants'?: number;
    /**
     * 모집 시작일
     * @type {Date}
     * @memberof CampaignBasicInfoResponseData
     */
    'recruitmentStartDate'?: Date;
    /**
     * 모집 종료일
     * @type {Date}
     * @memberof CampaignBasicInfoResponseData
     */
    'recruitmentEndDate'?: Date;
}


