/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 캠페인 썸네일 정보
 * @export
 * @interface CampaignThumbnailResponseData
 */
export interface CampaignThumbnailResponseData {
    /**
     * 캠페인 ID
     * @type {number}
     * @memberof CampaignThumbnailResponseData
     */
    'campaignId'?: number;
    /**
     * 썸네일 이미지 URL
     * @type {string}
     * @memberof CampaignThumbnailResponseData
     */
    'thumbnailUrl'?: string;
}



