/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignV1ListSuccessResponseDataCampaignsInnerCategory } from './campaign-v1-list-success-response-data-campaigns-inner-category';

/**
 * 
 * @export
 * @interface CampaignV1ListSuccessResponseDataCampaignsInner
 */
export interface CampaignV1ListSuccessResponseDataCampaignsInner {
    /**
     * 캠페인 ID
     * @type {number}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'id'?: number;
    /**
     * 캠페인 제목
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'title'?: string;
    /**
     * 캠페인 타입
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'campaignType'?: string;
    /**
     * 썸네일 URL
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'thumbnailUrl'?: string;
    /**
     * 제품 간단 정보
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'productShortInfo'?: string;
    /**
     * 최대 신청자 수
     * @type {number}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'maxApplicants'?: number;
    /**
     * 현재 신청자 수
     * @type {number}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'currentApplicants'?: number;
    /**
     * 모집 시작일
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'recruitmentStartDate'?: string;
    /**
     * 모집 종료일
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'recruitmentEndDate'?: string;
    /**
     * 신청 마감일
     * @type {string}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'applicationDeadlineDate'?: string;
    /**
     * 
     * @type {CampaignV1ListSuccessResponseDataCampaignsInnerCategory}
     * @memberof CampaignV1ListSuccessResponseDataCampaignsInner
     */
    'category'?: CampaignV1ListSuccessResponseDataCampaignsInnerCategory;
}
