/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 캠페인 카테고리
 * @export
 * @interface CategoryV2
 */
export interface CategoryV2 {
    /**
     * 카테고리 타입 V2 (OAS 표준 준수)
     * @type {string}
     * @memberof CategoryV2
     */
    'type': CategoryV2TypeEnum;
    /**
     * 카테고리 이름
     * @type {string}
     * @memberof CategoryV2
     */
    'name': string;
}


/**
    * @export
    * @enum {string}
    */
export type CategoryV2TypeEnum = 
  'VISIT'|
  'DELIVERY'



