/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 캠페인 카테고리 정보
 * @export
 * @interface CategoryInfo
 */
export interface CategoryInfo {
    /**
     * 카테고리 타입 - 캠페인 진행 방식을 구분하는 대분류
     * @type {string}
     * @memberof CategoryInfo
     */
    'type': CategoryInfoTypeEnum;
    /**
     * 카테고리명 - 제품/서비스 분야를 나타내는 세부 분류 • 방문형: 맛집, 카페, 뷰티, 숙박 • 배송형: 식품, 화장품, 생활용품, 패션, 잡화
     * @type {string}
     * @memberof CategoryInfo
     */
    'name': string;
}


/**
    * @export
    * @enum {string}
    */
export type CategoryInfoTypeEnum = 
  '방문'|
  '배송'



