/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 승인됐지만 신청기간이 종료된 캠페인
 * @export
 * @interface ClientCampaignSummaryResponseSummaryExpired
 */
export interface ClientCampaignSummaryResponseSummaryExpired {
    /**
     * 만료된 캠페인 수
     * @type {number}
     * @memberof ClientCampaignSummaryResponseSummaryExpired
     */
    'count'?: number;
    /**
     * 상태 레이블
     * @type {string}
     * @memberof ClientCampaignSummaryResponseSummaryExpired
     */
    'label'?: string;
}


