/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 관리자 승인 대기중인 캠페인
 * @export
 * @interface ClientCampaignSummaryResponseSummaryPending
 */
export interface ClientCampaignSummaryResponseSummaryPending {
    /**
     * 대기중인 캠페인 수
     * @type {number}
     * @memberof ClientCampaignSummaryResponseSummaryPending
     */
    'count'?: number;
    /**
     * 상태 레이블
     * @type {string}
     * @memberof ClientCampaignSummaryResponseSummaryPending
     */
    'label'?: string;
}
