/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClientCampaignSummaryResponseSummary } from './client-campaign-summary-response-summary';
import { ClientCampaignSummaryResponseSummary } from './client-campaign-summary-response-summary';
import { ClientCampaignSummaryResponseSummary } from './client-campaign-summary-response-summary';
import { ClientCampaignSummaryResponseSummary } from './client-campaign-summary-response-summary';

/**
 * 기업 캠페인 요약 정보
 * @export
 * @interface ClientCampaignSummaryResponseSummary
 */
export interface ClientCampaignSummaryResponseSummary {
    /**
     * 
     * @type {ClientCampaignSummaryResponseSummaryPending}
     * @memberof ClientCampaignSummaryResponseSummary
     */
    'pending'?: ClientCampaignSummaryResponseSummaryPending;
    /**
     * 
     * @type {ClientCampaignSummaryResponseSummaryApproved}
     * @memberof ClientCampaignSummaryResponseSummary
     */
    'approved'?: ClientCampaignSummaryResponseSummaryApproved;
    /**
     * 
     * @type {ClientCampaignSummaryResponseSummaryRejected}
     * @memberof ClientCampaignSummaryResponseSummary
     */
    'rejected'?: ClientCampaignSummaryResponseSummaryRejected;
    /**
     * 
     * @type {ClientCampaignSummaryResponseSummaryExpired}
     * @memberof ClientCampaignSummaryResponseSummary
     */
    'expired'?: ClientCampaignSummaryResponseSummaryExpired;
}


