/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 캠페인 주최 업체 정보
 * @export
 * @interface CompanyInfo
 */
export interface CompanyInfo {
    /**
     * 업체명 - 캠페인을 주최하는 회사/브랜드 이름
     * @type {string}
     * @memberof CompanyInfo
     */
    'companyName': string;
    /**
     * 사업자등록번호 - 업체의 공식 등록번호 (선택사항)
     * @type {string}
     * @memberof CompanyInfo
     */
    'businessRegistrationNumber'?: string;
    /**
     * 담당자명 - 캠페인 관련 문의 시 연락할 담당자 이름
     * @type {string}
     * @memberof CompanyInfo
     */
    'contactPerson'?: string;
    /**
     * 연락처 - 담당자의 전화번호 또는 연락 가능한 번호
     * @type {string}
     * @memberof CompanyInfo
     */
    'phoneNumber'?: string;
}
