/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 회사 정보 (OAS 표준)
 * @export
 * @interface CreateCampaignV2ResponseCompanyInfo
 */
export interface CreateCampaignV2ResponseCompanyInfo {
    /**
     * 회사 ID
     * @type {number}
     * @memberof CreateCampaignV2ResponseCompanyInfo
     */
    'id'?: number;
    /**
     * 회사명
     * @type {string}
     * @memberof CreateCampaignV2ResponseCompanyInfo
     */
    'companyName'?: string;
    /**
     * 사업자등록번호
     * @type {string}
     * @memberof CreateCampaignV2ResponseCompanyInfo
     */
    'businessRegistrationNumber'?: string;
    /**
     * 담당자명
     * @type {string}
     * @memberof CreateCampaignV2ResponseCompanyInfo
     */
    'contactPerson'?: string;
    /**
     * 연락처
     * @type {string}
     * @memberof CreateCampaignV2ResponseCompanyInfo
     */
    'phoneNumber'?: string;
    /**
     * 생성 일시
     * @type {Date}
     * @memberof CreateCampaignV2ResponseCompanyInfo
     */
    'createdAt'?: Date;
    /**
     * 수정 일시
     * @type {Date}
     * @memberof CreateCampaignV2ResponseCompanyInfo
     */
    'updatedAt'?: Date;
}


