/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 캠페인 카테고리 (OAS 표준)
 * @export
 * @interface CreateCampaignV2ResponseCategory
 */
export interface CreateCampaignV2ResponseCategory {
    /**
     * 카테고리 ID
     * @type {number}
     * @memberof CreateCampaignV2ResponseCategory
     */
    'id'?: number;
    /**
     * 카테고리 타입 (OAS 표준)
     * @type {string}
     * @memberof CreateCampaignV2ResponseCategory
     */
    'type'?: CreateCampaignV2ResponseCategoryTypeEnum;
    /**
     * 카테고리 이름
     * @type {string}
     * @memberof CreateCampaignV2ResponseCategory
     */
    'name'?: string;
    /**
     * 생성 일시
     * @type {Date}
     * @memberof CreateCampaignV2ResponseCategory
     */
    'createdAt'?: Date;
    /**
     * 수정 일시
     * @type {Date}
     * @memberof CreateCampaignV2ResponseCategory
     */
    'updatedAt'?: Date;
}

/**
    * @export
    * @enum {string}
    */
export type CreateCampaignV2ResponseCategoryTypeEnum = 
  'VISIT'|
  'DELIVERY'



