/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryV2 } from './category-v2';
import { CompanyInfo } from './company-info';

/**
 * 캠페인 생성 요청
 * @export
 * @interface CreateCampaignV2Request
 */
export interface CreateCampaignV2Request {
    /**
     * 캠페인 썸네일 이미지 URL
     * @type {string}
     * @memberof CreateCampaignV2Request
     */
    'thumbnailUrl': string;
    /**
     * 캠페인 타입 V2 (OAS 표준 준수)
     * @type {string}
     * @memberof CreateCampaignV2Request
     */
    'campaignType': CreateCampaignV2RequestCampaignTypeEnum;
    /**
     * 캠페인 제목
     * @type {string}
     * @memberof CreateCampaignV2Request
     */
    'title': string;
    /**
     * 제품 간단 정보
     * @type {string}
     * @memberof CreateCampaignV2Request
     */
    'productShortInfo': string;
    /**
     * 최대 신청자 수
     * @type {number}
     * @memberof CreateCampaignV2Request
     */
    'maxApplicants': number;
    /**
     * 제품 상세 정보
     * @type {string}
     * @memberof CreateCampaignV2Request
     */
    'productDetails': string;
    /**
     * 모집 시작일
     * @type {Date}
     * @memberof CreateCampaignV2Request
     */
    'recruitmentStartDate': Date;
    /**
     * 모집 종료일
     * @type {Date}
     * @memberof CreateCampaignV2Request
     */
    'recruitmentEndDate': Date;
    /**
     * 신청 마감일
     * @type {Date}
     * @memberof CreateCampaignV2Request
     */
    'applicationDeadlineDate': Date;
    /**
     * 참여자 선정일
     * @type {Date}
     * @memberof CreateCampaignV2Request
     */
    'selectionDate': Date;
    /**
     * 리뷰 제출 마감일
     * @type {Date}
     * @memberof CreateCampaignV2Request
     */
    'reviewDeadlineDate': Date;
    /**
     * 선정 기준
     * @type {string}
     * @memberof CreateCampaignV2Request
     */
    'selectionCriteria': string;
    /**
     * 미션 가이드
     * @type {string}
     * @memberof CreateCampaignV2Request
     */
    'missionGuide': string;
    /**
     * 미션 키워드
     * @type {Array<string>}
     * @memberof CreateCampaignV2Request
     */
    'missionKeywords': Array<string>;
    /**
     * 
     * @type {CategoryV2}
     * @memberof CreateCampaignV2Request
     */
    'category': CategoryV2;
    /**
     * 
     * @type {CompanyInfo}
     * @memberof CreateCampaignV2Request
     */
    'companyInfo': CompanyInfo;
}

/**
    * @export
    * @enum {string}
    */
export type CreateCampaignV2RequestCampaignTypeEnum = 
  'INSTAGRAM'|
  'BLOG'|
  'YOUTUBE'|
  'INSTAGRAM'|
  'BLOG'|
  'YOUTUBE'



