/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 이메일 회원가입 요청
 * @export
 * @interface EmailSignupRequest
 */
export interface EmailSignupRequest {
    /**
     * 사용자 이메일
     * @type {string}
     * @memberof EmailSignupRequest
     */
    'email': string;
    /**
     * 비밀번호 (8-20자)
     * @type {string}
     * @memberof EmailSignupRequest
     */
    'password': string;
    /**
     * 닉네임 (2-8자)
     * @type {string}
     * @memberof EmailSignupRequest
     */
    'nickname': string;
}


