/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 카카오 로그인 요청
 * @export
 * @interface KakaoAuthRequest
 */
export interface KakaoAuthRequest {
    /**
     * 카카오 OAuth 인가 코드
     * @type {string}
     * @memberof KakaoAuthRequest
     */
    'authorizationCode': string;
    /**
     * 리다이렉트 URI
     * @type {string}
     * @memberof KakaoAuthRequest
     */
    'redirectUri': KakaoAuthRequestRedirectUriEnum;
}

/**
    * @export
    * @enum {string}
    */
export type KakaoAuthRequestRedirectUriEnum = 
  'http://localhost:3000/login/oauth2/code/kakao'|
  'https://chkok.kr/login/oauth2/code/kakao'



