/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface LikeToggleSuccessResponseData
 */
export interface LikeToggleSuccessResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof LikeToggleSuccessResponseData
     */
    'liked'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof LikeToggleSuccessResponseData
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof LikeToggleSuccessResponseData
     */
    'campaignId'?: number;
}


