/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfo } from './user-info';

/**
 * 로그인 데이터
 * @export
 * @interface LoginData
 */
export interface LoginData {
    /**
     * 로그인 타입
     * @type {string}
     * @memberof LoginData
     */
    'loginType'?: LoginDataLoginTypeEnum;
    /**
     * 액세스 토큰
     * @type {string}
     * @memberof LoginData
     */
    'accessToken'?: string;
    /**
     * 리프레시 토큰
     * @type {string}
     * @memberof LoginData
     */
    'refreshToken'?: string;
    /**
     * 
     * @type {UserInfo}
     * @memberof LoginData
     */
    'user'?: UserInfo;
}


/**
    * @export
    * @enum {string}
    */
export type LoginDataLoginTypeEnum = 
  'login'|
  'registration'



