/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyApplicationsSuccessResponseDataApplicationsInnerCampaign } from './my-applications-success-response-data-applications-inner-campaign';

/**
 * 
 * @export
 * @interface MyApplicationsSuccessResponseDataApplicationsInner
 */
export interface MyApplicationsSuccessResponseDataApplicationsInner {
    /**
     * 
     * @type {number}
     * @memberof MyApplicationsSuccessResponseDataApplicationsInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MyApplicationsSuccessResponseDataApplicationsInner
     */
    'applicationStatus'?: string;
    /**
     * 
     * @type {MyApplicationsSuccessResponseDataApplicationsInnerCampaign}
     * @memberof MyApplicationsSuccessResponseDataApplicationsInner
     */
    'campaign'?: MyApplicationsSuccessResponseDataApplicationsInnerCampaign;
}


