/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClientCampaignSummaryResponse } from './ClientCampaignSummaryResponse';
import {
    instanceOfClientCampaignSummaryResponse,
    ClientCampaignSummaryResponseFromJSON,
    ClientCampaignSummaryResponseFromJSONTyped,
    ClientCampaignSummaryResponseToJSON,
} from './ClientCampaignSummaryResponse';
import type { UserCampaignSummaryResponse } from './UserCampaignSummaryResponse';
import {
    instanceOfUserCampaignSummaryResponse,
    UserCampaignSummaryResponseFromJSON,
    UserCampaignSummaryResponseFromJSONTyped,
    UserCampaignSummaryResponseToJSON,
} from './UserCampaignSummaryResponse';

/**
 * @type MyCampaignSuccessResponseData
 * 역할별 캠페인 요약 데이터
 * @export
 */
export type MyCampaignSuccessResponseData = ClientCampaignSummaryResponse | UserCampaignSummaryResponse;

export function MyCampaignSuccessResponseDataFromJSON(json: any): MyCampaignSuccessResponseData {
    return MyCampaignSuccessResponseDataFromJSONTyped(json, false);
}

export function MyCampaignSuccessResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyCampaignSuccessResponseData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfClientCampaignSummaryResponse(json)) {
        return ClientCampaignSummaryResponseFromJSONTyped(json, true);
    }
    if (instanceOfUserCampaignSummaryResponse(json)) {
        return UserCampaignSummaryResponseFromJSONTyped(json, true);
    }

    return {} as any;
}

export function MyCampaignSuccessResponseDataToJSON(json: any): any {
    return MyCampaignSuccessResponseDataToJSONTyped(json, false);
}

export function MyCampaignSuccessResponseDataToJSONTyped(value?: MyCampaignSuccessResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfClientCampaignSummaryResponse(value)) {
        return ClientCampaignSummaryResponseToJSON(value as ClientCampaignSummaryResponse);
    }
    if (instanceOfUserCampaignSummaryResponse(value)) {
        return UserCampaignSummaryResponseToJSON(value as UserCampaignSummaryResponse);
    }

    return {};
}

