/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlatformListSuccessResponseData } from './platform-list-success-response-data';

/**
 * 플랫폼 목록 데이터
 * @export
 * @interface PlatformListSuccessResponseData
 */
export interface PlatformListSuccessResponseData {
    /**
     * 연동된 플랫폼 목록
     * @type {Array<PlatformListSuccessResponseDataPlatformsInner>}
     * @memberof PlatformListSuccessResponseData
     */
    'platforms'?: Array<PlatformListSuccessResponseDataPlatformsInner>;
}


