/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 연동 결과 데이터
 * @export
 * @interface PlatformConnectSuccessResponseData
 */
export interface PlatformConnectSuccessResponseData {
    /**
     * 생성된 플랫폼 ID
     * @type {number}
     * @memberof PlatformConnectSuccessResponseData
     */
    'platformId'?: number;
    /**
     * 플랫폼 타입
     * @type {string}
     * @memberof PlatformConnectSuccessResponseData
     */
    'platformType'?: string;
    /**
     * 연동 완료 메시지
     * @type {string}
     * @memberof PlatformConnectSuccessResponseData
     */
    'message'?: string;
}
