/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PlatformListSuccessResponseDataPlatformsInner
 */
export interface PlatformListSuccessResponseDataPlatformsInner {
    /**
     * 플랫폼 ID
     * @type {number}
     * @memberof PlatformListSuccessResponseDataPlatformsInner
     */
    'id'?: number;
    /**
     * 플랫폼 타입
     * @type {string}
     * @memberof PlatformListSuccessResponseDataPlatformsInner
     */
    'platformType'?: string;
    /**
     * 계정 URL
     * @type {string}
     * @memberof PlatformListSuccessResponseDataPlatformsInner
     */
    'accountUrl'?: string;
    /**
     * 팔로워 수
     * @type {number}
     * @memberof PlatformListSuccessResponseDataPlatformsInner
     */
    'followerCount'?: number;
    /**
     * 마지막 크롤링 시간
     * @type {string}
     * @memberof PlatformListSuccessResponseDataPlatformsInner
     */
    'lastCrawledAt'?: string;
}



