/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * SNS 플랫폼 연동 요청
 * @export
 * @interface PlatformConnectRequest
 */
export interface PlatformConnectRequest {
    /**
     * 플랫폼 타입
     * @type {string}
     * @memberof PlatformConnectRequest
     */
    'type': PlatformConnectRequestTypeEnum;
    /**
     * SNS 플랫폼 URL
     * @type {string}
     * @memberof PlatformConnectRequest
     */
    'url': string;
}


/**
    * @export
    * @enum {string}
    */
export type PlatformConnectRequestTypeEnum = 
  'BLOG'|
  'INSTAGRAM'|
  'YOUTUBE'



