/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 파일 정보
 * @export
 * @interface PresignedUrlRequest
 */
export interface PresignedUrlRequest {
    /**
     * 파일 확장자
     * @type {string}
     * @memberof PresignedUrlRequest
     */
    'fileExtension': string;
}

/**
 * @export
 * @enum {string}
 */
export enum FileExtensionEnum {
    'jpg' = 'jpg',
    'jpeg' = 'jpeg',
    'png' = 'png'
}

