/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 프로필 이미지 수정 요청
 * @export
 * @interface ProfileImageUpdateRequest
 */
export interface ProfileImageUpdateRequest {
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof ProfileImageUpdateRequest
     */
    'profileImage': string;
}


