/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 인기 검색어 데이터
 * @export
 * @interface RealtimeSearchSuccessResponseData
 */
export interface RealtimeSearchSuccessResponseData {
    /**
     * 실시간 인기 검색어 목록
     * @type {Array<string>}
     * @memberof RealtimeSearchSuccessResponseData
     */
    'suggestions'?: Array<string>;
}
