/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 토큰 데이터
 * @export
 * @interface TokenData
 */
export interface TokenData {
    /**
     * 새 액세스 토큰
     * @type {string}
     * @memberof TokenData
     */
    'accessToken'?: string;
    /**
     * 새 리프레시 토큰
     * @type {string}
     * @memberof TokenData
     */
    'refreshToken'?: string;
}
