/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 총 지원한 신청
 * @export
 * @interface UserCampaignSummaryResponseSummaryApplied
 */
export interface UserCampaignSummaryResponseSummaryApplied {
    /**
     * 총 지원 신청 수
     * @type {number}
     * @memberof UserCampaignSummaryResponseSummaryApplied
     */
    'count'?: number;
    /**
     * 상태 레이블
     * @type {string}
     * @memberof UserCampaignSummaryResponseSummaryApplied
     */
    'label'?: string;
}


