/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 사용자 정보
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 사용자 ID
     * @type {number}
     * @memberof UserInfo
     */
    'id'?: number;
    /**
     * 이메일
     * @type {string}
     * @memberof UserInfo
     */
    'email'?: string;
    /**
     * 닉네임
     * @type {string}
     * @memberof UserInfo
     */
    'nickname'?: string;
    /**
     * 권한
     * @type {string}
     * @memberof UserInfo
     */
    'role'?: string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserInfo
     */
    'profileImageUrl'?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum RoleEnum {
    'USER' = 'USER',
    'CLIENT' = 'CLIENT',
    'ADMIN' = 'ADMIN'
}

