/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCampaignSummaryResponseSummaryApplied } from './user-campaign-summary-response-summary-applied';
import { UserCampaignSummaryResponseSummaryCompleted } from './user-campaign-summary-response-summary-completed';
import { UserCampaignSummaryResponseSummaryPending } from './user-campaign-summary-response-summary-pending';
import { UserCampaignSummaryResponseSummarySelected } from './user-campaign-summary-response-summary-selected';

/**
 * 인플루언서 신청 요약 정보
 * @export
 * @interface UserCampaignSummaryResponseSummary
 */
export interface UserCampaignSummaryResponseSummary {
    /**
     * 
     * @type {UserCampaignSummaryResponseSummaryApplied}
     * @memberof UserCampaignSummaryResponseSummary
     */
    'applied'?: UserCampaignSummaryResponseSummaryApplied;
    /**
     * 
     * @type {UserCampaignSummaryResponseSummaryPending}
     * @memberof UserCampaignSummaryResponseSummary
     */
    'pending'?: UserCampaignSummaryResponseSummaryPending;
    /**
     * 
     * @type {UserCampaignSummaryResponseSummarySelected}
     * @memberof UserCampaignSummaryResponseSummary
     */
    'selected'?: UserCampaignSummaryResponseSummarySelected;
    /**
     * 
     * @type {UserCampaignSummaryResponseSummaryCompleted}
     * @memberof UserCampaignSummaryResponseSummary
     */
    'completed'?: UserCampaignSummaryResponseSummaryCompleted;
}



