/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 API
 * 체험콕 캠페인 플랫폼 API 문서
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * 수정할 사용자 정보
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
    /**
     * 닉네임 (2~8자)
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'nickname'?: string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'profileImage'?: string;
    /**
     * 전화번호
     * @type {string}
     * @memberof UserUpdateRequest
     */
    'phone'?: string;
    /**
     * 
     * @type {Gender}
     * @memberof UserUpdateRequest
     */
    'gender'?: Gender;
    /**
     * 나이
     * @type {number}
     * @memberof UserUpdateRequest
     */
    'age'?: number;
}


