/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseError
 */
export interface BaseResponseError {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseError
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseError
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseError
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseError
     */
    errorCode?: string;
}

/**
 * Check if a given object implements the BaseResponseError interface.
 */
export function instanceOfBaseResponseError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaseResponseErrorFromJSON(json: any): BaseResponseError {
    return BaseResponseErrorFromJSONTyped(json, false);
}

export function BaseResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
    };
}

export function BaseResponseErrorToJSON(value?: BaseResponseError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'status': value.status,
        'errorCode': value.errorCode,
    };
}

