/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseSuccess
 */
export interface BaseResponseSuccess {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseSuccess
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseSuccess
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseSuccess
     */
    status?: number;
    /**
     * 
     * @type {object}
     * @memberof BaseResponseSuccess
     */
    data?: object;
}

/**
 * Check if a given object implements the BaseResponseSuccess interface.
 */
export function instanceOfBaseResponseSuccess(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaseResponseSuccessFromJSON(json: any): BaseResponseSuccess {
    return BaseResponseSuccessFromJSONTyped(json, false);
}

export function BaseResponseSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseSuccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function BaseResponseSuccessToJSON(value?: BaseResponseSuccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'status': value.status,
        'data': value.data,
    };
}

