/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 캠페인 신청 요청 DTO
 * @export
 * @interface CampaignApplicationRequest
 */
export interface CampaignApplicationRequest {
    /**
     * 신청할 캠페인의 고유 식별자
     * @type {number}
     * @memberof CampaignApplicationRequest
     */
    campaignId: number;
}

/**
 * Check if a given object implements the CampaignApplicationRequest interface.
 */
export function instanceOfCampaignApplicationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "campaignId" in value;

    return isInstance;
}

export function CampaignApplicationRequestFromJSON(json: any): CampaignApplicationRequest {
    return CampaignApplicationRequestFromJSONTyped(json, false);
}

export function CampaignApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignApplicationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'campaignId': json['campaignId'],
    };
}

export function CampaignApplicationRequestToJSON(value?: CampaignApplicationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'campaignId': value.campaignId,
    };
}

