/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 🏷️ 캠페인 카테고리 정보
 * @export
 * @interface CategoryInfo
 */
export interface CategoryInfo {
    /**
     * 카테고리 타입 - 캠페인 진행 방식을 구분하는 대분류
     * @type {string}
     * @memberof CategoryInfo
     */
    type: CategoryInfoTypeEnum;
    /**
     * 카테고리명 - 제품/서비스 분야를 나타내는 세부 분류
     * • 방문형: 맛집, 카페, 뷰티, 숙박
     * • 배송형: 식품, 화장품, 생활용품, 패션, 잡화
     * @type {string}
     * @memberof CategoryInfo
     */
    name: string;
}

/**
* @export
* @enum {string}
*/
export enum CategoryInfoTypeEnum {
     = '방문',
    2 = '배송'
}


/**
 * Check if a given object implements the CategoryInfo interface.
 */
export function instanceOfCategoryInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CategoryInfoFromJSON(json: any): CategoryInfo {
    return CategoryInfoFromJSONTyped(json, false);
}

export function CategoryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
    };
}

export function CategoryInfoToJSON(value?: CategoryInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'name': value.name,
    };
}

