/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseDTO
 */
export interface ErrorResponseDTO {
    /**
     * 성공 여부 (항상 false)
     * @type {boolean}
     * @memberof ErrorResponseDTO
     */
    success?: boolean;
    /**
     * 오류 메시지
     * @type {string}
     * @memberof ErrorResponseDTO
     */
    message?: string;
    /**
     * 오류 코드
     * @type {string}
     * @memberof ErrorResponseDTO
     */
    errorCode?: ErrorResponseDTOErrorCodeEnum;
    /**
     * HTTP 상태 코드
     * @type {number}
     * @memberof ErrorResponseDTO
     */
    status?: number;
}

/**
* @export
* @enum {string}
*/
export enum ErrorResponseDTOErrorCodeEnum {
    Unauthorized = 'UNAUTHORIZED',
    TokenExpired = 'TOKEN_EXPIRED',
    InvalidRefreshToken = 'INVALID_REFRESH_TOKEN',
    ValidationError = 'VALIDATION_ERROR',
    ResourceNotFound = 'RESOURCE_NOT_FOUND',
    InternalError = 'INTERNAL_ERROR'
}


/**
 * Check if a given object implements the ErrorResponseDTO interface.
 */
export function instanceOfErrorResponseDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorResponseDTOFromJSON(json: any): ErrorResponseDTO {
    return ErrorResponseDTOFromJSONTyped(json, false);
}

export function ErrorResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ErrorResponseDTOToJSON(value?: ErrorResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'errorCode': value.errorCode,
        'status': value.status,
    };
}

