/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 팔로워 수 업데이트 요청
 * @export
 * @interface FollowerCountUpdateRequest
 */
export interface FollowerCountUpdateRequest {
    /**
     * 팔로워/구독자 수
     * @type {number}
     * @memberof FollowerCountUpdateRequest
     */
    followerCount: number;
}

/**
 * Check if a given object implements the FollowerCountUpdateRequest interface.
 */
export function instanceOfFollowerCountUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "followerCount" in value;

    return isInstance;
}

export function FollowerCountUpdateRequestFromJSON(json: any): FollowerCountUpdateRequest {
    return FollowerCountUpdateRequestFromJSONTyped(json, false);
}

export function FollowerCountUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowerCountUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'followerCount': json['followerCount'],
    };
}

export function FollowerCountUpdateRequestToJSON(value?: FollowerCountUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'followerCount': value.followerCount,
    };
}

