/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KakaoAuthRequest
 */
export interface KakaoAuthRequest {
    /**
     * 카카오로부터 받은 인가 코드
     * @type {string}
     * @memberof KakaoAuthRequest
     */
    authorizationCode: string;
    /**
     * 리다이렉트 URI
     * @type {string}
     * @memberof KakaoAuthRequest
     */
    redirectUri: KakaoAuthRequestRedirectUriEnum;
}

/**
* @export
* @enum {string}
*/
export enum KakaoAuthRequestRedirectUriEnum {
    HttpLocalhost3000LoginOauth2CodeKakao = 'http://localhost:3000/login/oauth2/code/kakao',
    HttpsCkokKrLoginOauth2CodeKakao = 'https://ckok.kr/login/oauth2/code/kakao'
}


/**
 * Check if a given object implements the KakaoAuthRequest interface.
 */
export function instanceOfKakaoAuthRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authorizationCode" in value;
    isInstance = isInstance && "redirectUri" in value;

    return isInstance;
}

export function KakaoAuthRequestFromJSON(json: any): KakaoAuthRequest {
    return KakaoAuthRequestFromJSONTyped(json, false);
}

export function KakaoAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KakaoAuthRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorizationCode': json['authorizationCode'],
        'redirectUri': json['redirectUri'],
    };
}

export function KakaoAuthRequestToJSON(value?: KakaoAuthRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorizationCode': value.authorizationCode,
        'redirectUri': value.redirectUri,
    };
}

