/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LoginDataDTO } from './LoginDataDTO';
import {
    LoginDataDTOFromJSON,
    LoginDataDTOFromJSONTyped,
    LoginDataDTOToJSON,
} from './LoginDataDTO';

/**
 * 
 * @export
 * @interface LoginResponseDTO
 */
export interface LoginResponseDTO {
    /**
     * 성공 여부
     * @type {boolean}
     * @memberof LoginResponseDTO
     */
    success?: boolean;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof LoginResponseDTO
     */
    message?: string;
    /**
     * HTTP 상태 코드
     * @type {number}
     * @memberof LoginResponseDTO
     */
    status?: number;
    /**
     * 
     * @type {LoginDataDTO}
     * @memberof LoginResponseDTO
     */
    data?: LoginDataDTO;
}

/**
 * Check if a given object implements the LoginResponseDTO interface.
 */
export function instanceOfLoginResponseDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginResponseDTOFromJSON(json: any): LoginResponseDTO {
    return LoginResponseDTOFromJSONTyped(json, false);
}

export function LoginResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'data': !exists(json, 'data') ? undefined : LoginDataDTOFromJSON(json['data']),
    };
}

export function LoginResponseDTOToJSON(value?: LoginResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'status': value.status,
        'data': LoginDataDTOToJSON(value.data),
    };
}

