/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 오류 응답
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 성공 여부
     * @type {boolean}
     * @memberof ModelError
     */
    success?: boolean;
    /**
     * 오류 메시지
     * @type {string}
     * @memberof ModelError
     */
    message?: string;
    /**
     * 오류 코드
     * @type {string}
     * @memberof ModelError
     */
    errorCode?: string;
    /**
     * HTTP 상태 코드
     * @type {number}
     * @memberof ModelError
     */
    status?: number;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'errorCode': value.errorCode,
        'status': value.status,
    };
}

