/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NicknameUpdateRequest
 */
export interface NicknameUpdateRequest {
    /**
     * 닉네임 (2~8자)
     * @type {string}
     * @memberof NicknameUpdateRequest
     */
    nickname: string;
}

/**
 * Check if a given object implements the NicknameUpdateRequest interface.
 */
export function instanceOfNicknameUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nickname" in value;

    return isInstance;
}

export function NicknameUpdateRequestFromJSON(json: any): NicknameUpdateRequest {
    return NicknameUpdateRequestFromJSONTyped(json, false);
}

export function NicknameUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NicknameUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
    };
}

export function NicknameUpdateRequestToJSON(value?: NicknameUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nickname': value.nickname,
    };
}

