/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * SNS 플랫폼 유형: BLOG(블로그), INSTAGRAM(인스타그램), YOUTUBE(유튜브)
 * @export
 * @enum {string}
 */
export enum PlatformType {
    Blog = 'blog',
    Facebook = 'facebook',
    Instagram = 'instagram',
    Youtube = 'youtube'
}


export function PlatformTypeFromJSON(json: any): PlatformType {
    return PlatformTypeFromJSONTyped(json, false);
}

export function PlatformTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformType {
    return json as PlatformType;
}

export function PlatformTypeToJSON(value?: PlatformType | null): any {
    return value as any;
}

