/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SNS 플랫폼 연동 요청
 * @export
 * @interface PlatformConnectRequest
 */
export interface PlatformConnectRequest {
    /**
     * 
     * @type {string}
     * @memberof PlatformConnectRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformConnectRequest
     */
    url: string;
}

/**
 * Check if a given object implements the PlatformConnectRequest interface.
 */
export function instanceOfPlatformConnectRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function PlatformConnectRequestFromJSON(json: any): PlatformConnectRequest {
    return PlatformConnectRequestFromJSONTyped(json, false);
}

export function PlatformConnectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformConnectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url': json['url'],
    };
}

export function PlatformConnectRequestToJSON(value?: PlatformConnectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'url': value.url,
    };
}

