/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 파일 정보
 * @export
 * @interface PresignedUrlRequest
 */
export interface PresignedUrlRequest {
    /**
     * 
     * @type {string}
     * @memberof PresignedUrlRequest
     */
    fileExtension: string;
}

/**
 * Check if a given object implements the PresignedUrlRequest interface.
 */
export function instanceOfPresignedUrlRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fileExtension" in value;

    return isInstance;
}

export function PresignedUrlRequestFromJSON(json: any): PresignedUrlRequest {
    return PresignedUrlRequestFromJSONTyped(json, false);
}

export function PresignedUrlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignedUrlRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fileExtension': json['fileExtension'],
    };
}

export function PresignedUrlRequestToJSON(value?: PresignedUrlRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fileExtension': value.fileExtension,
    };
}

