/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileImageUpdateRequest
 */
export interface ProfileImageUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ProfileImageUpdateRequest
     */
    profileImage: string;
}

/**
 * Check if a given object implements the ProfileImageUpdateRequest interface.
 */
export function instanceOfProfileImageUpdateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profileImage" in value;

    return isInstance;
}

export function ProfileImageUpdateRequestFromJSON(json: any): ProfileImageUpdateRequest {
    return ProfileImageUpdateRequestFromJSONTyped(json, false);
}

export function ProfileImageUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileImageUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileImage': json['profileImage'],
    };
}

export function ProfileImageUpdateRequestToJSON(value?: ProfileImageUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profileImage': value.profileImage,
    };
}

