/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 성공 응답
 * @export
 * @interface Success
 */
export interface Success {
    /**
     * 성공 여부
     * @type {boolean}
     * @memberof Success
     */
    success?: boolean;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof Success
     */
    message?: string;
    /**
     * HTTP 상태 코드
     * @type {number}
     * @memberof Success
     */
    status?: number;
    /**
     * 응답 데이터
     * @type {object}
     * @memberof Success
     */
    data?: object;
}

/**
 * Check if a given object implements the Success interface.
 */
export function instanceOfSuccess(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SuccessFromJSON(json: any): Success {
    return SuccessFromJSONTyped(json, false);
}

export function SuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): Success {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function SuccessToJSON(value?: Success | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'status': value.status,
        'data': value.data,
    };
}

