/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TokenRefreshDataDTO } from './TokenRefreshDataDTO';
import {
    TokenRefreshDataDTOFromJSON,
    TokenRefreshDataDTOFromJSONTyped,
    TokenRefreshDataDTOToJSON,
} from './TokenRefreshDataDTO';

/**
 * 
 * @export
 * @interface TokenRefreshResponseDTO
 */
export interface TokenRefreshResponseDTO {
    /**
     * 성공 여부
     * @type {boolean}
     * @memberof TokenRefreshResponseDTO
     */
    success?: boolean;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof TokenRefreshResponseDTO
     */
    message?: string;
    /**
     * HTTP 상태 코드
     * @type {number}
     * @memberof TokenRefreshResponseDTO
     */
    status?: number;
    /**
     * 
     * @type {TokenRefreshDataDTO}
     * @memberof TokenRefreshResponseDTO
     */
    data?: TokenRefreshDataDTO;
}

/**
 * Check if a given object implements the TokenRefreshResponseDTO interface.
 */
export function instanceOfTokenRefreshResponseDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenRefreshResponseDTOFromJSON(json: any): TokenRefreshResponseDTO {
    return TokenRefreshResponseDTOFromJSONTyped(json, false);
}

export function TokenRefreshResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRefreshResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'data': !exists(json, 'data') ? undefined : TokenRefreshDataDTOFromJSON(json['data']),
    };
}

export function TokenRefreshResponseDTOToJSON(value?: TokenRefreshResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'status': value.status,
        'data': TokenRefreshDataDTOToJSON(value.data),
    };
}

