/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 응답 데이터
 * @export
 * @interface TokenRefreshDataDTO
 */
export interface TokenRefreshDataDTO {
    /**
     * 새 액세스 토큰
     * @type {string}
     * @memberof TokenRefreshDataDTO
     */
    accessToken?: string;
    /**
     * 새 리프레시 토큰
     * @type {string}
     * @memberof TokenRefreshDataDTO
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the TokenRefreshDataDTO interface.
 */
export function instanceOfTokenRefreshDataDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenRefreshDataDTOFromJSON(json: any): TokenRefreshDataDTO {
    return TokenRefreshDataDTOFromJSONTyped(json, false);
}

export function TokenRefreshDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRefreshDataDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'refreshToken': !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
    };
}

export function TokenRefreshDataDTOToJSON(value?: TokenRefreshDataDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'refreshToken': value.refreshToken,
    };
}

