/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 수정할 사용자 정보
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
    /**
     * 닉네임 (2~8자)
     * @type {string}
     * @memberof UserUpdateRequest
     */
    nickname?: string | null;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserUpdateRequest
     */
    profileImage?: string | null;
    /**
     * 전화번호
     * @type {string}
     * @memberof UserUpdateRequest
     */
    phone?: string | null;
    /**
     * 성별
     * @type {string}
     * @memberof UserUpdateRequest
     */
    gender?: UserUpdateRequestGenderEnum;
    /**
     * 나이 (정수)
     * @type {number}
     * @memberof UserUpdateRequest
     */
    age?: number | null;
}

/**
* @export
* @enum {string}
*/
export enum UserUpdateRequestGenderEnum {
    Male = 'MALE',
    Female = 'FEMALE',
    Unknown = 'UNKNOWN'
}


/**
 * Check if a given object implements the UserUpdateRequest interface.
 */
export function instanceOfUserUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserUpdateRequestFromJSON(json: any): UserUpdateRequest {
    return UserUpdateRequestFromJSONTyped(json, false);
}

export function UserUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'profileImage': !exists(json, 'profileImage') ? undefined : json['profileImage'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'age': !exists(json, 'age') ? undefined : json['age'],
    };
}

export function UserUpdateRequestToJSON(value?: UserUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nickname': value.nickname,
        'profileImage': value.profileImage,
        'phone': value.phone,
        'gender': value.gender,
        'age': value.age,
    };
}

