/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 응답 데이터
 * @export
 * @interface UserProfileDataDTO
 */
export interface UserProfileDataDTO {
    /**
     * 
     * @type {UserDTO}
     * @memberof UserProfileDataDTO
     */
    user?: UserDTO;
}

/**
 * Check if a given object implements the UserProfileDataDTO interface.
 */
export function instanceOfUserProfileDataDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfileDataDTOFromJSON(json: any): UserProfileDataDTO {
    return UserProfileDataDTOFromJSONTyped(json, false);
}

export function UserProfileDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDataDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserDTOFromJSON(json['user']),
    };
}

export function UserProfileDataDTOToJSON(value?: UserProfileDataDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserDTOToJSON(value.user),
    };
}

