/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 사용자 정보
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 사용자 ID
     * @type {number}
     * @memberof UserDTO
     */
    id?: number;
    /**
     * 이메일
     * @type {string}
     * @memberof UserDTO
     */
    email?: string | null;
    /**
     * 닉네임
     * @type {string}
     * @memberof UserDTO
     */
    nickname?: string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserDTO
     */
    profileImage?: string | null;
    /**
     * 전화번호
     * @type {string}
     * @memberof UserDTO
     */
    phone?: string | null;
    /**
     * 성별
     * @type {string}
     * @memberof UserDTO
     */
    gender?: UserDTOGenderEnum;
    /**
     * 나이
     * @type {number}
     * @memberof UserDTO
     */
    age?: number | null;
    /**
     * 권한
     * @type {string}
     * @memberof UserDTO
     */
    role?: UserDTORoleEnum;
}

/**
* @export
* @enum {string}
*/
export enum UserDTOGenderEnum {
    Male = 'MALE',
    Female = 'FEMALE',
    Unknown = 'UNKNOWN'
}
/**
* @export
* @enum {string}
*/
export enum UserDTORoleEnum {
    User = 'USER',
    Client = 'CLIENT',
    Admin = 'ADMIN'
}


/**
 * Check if a given object implements the UserDTO interface.
 */
export function instanceOfUserDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'profileImage': !exists(json, 'profileImage') ? undefined : json['profileImage'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'age': !exists(json, 'age') ? undefined : json['age'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function UserDTOToJSON(value?: UserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'nickname': value.nickname,
        'profileImage': value.profileImage,
        'phone': value.phone,
        'gender': value.gender,
        'age': value.age,
        'role': value.role,
    };
}

