/* tslint:disable */
/* eslint-disable */
/**
 * 체험콕 서비스
 * 체험단 모집 및 관리 서비스 API
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserProfileDataDTO } from './UserProfileDataDTO';
import {
    UserProfileDataDTOFromJSON,
    UserProfileDataDTOFromJSONTyped,
    UserProfileDataDTOToJSON,
} from './UserProfileDataDTO';

/**
 * 
 * @export
 * @interface UserProfileResponseDTO
 */
export interface UserProfileResponseDTO {
    /**
     * 성공 여부
     * @type {boolean}
     * @memberof UserProfileResponseDTO
     */
    success?: boolean;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof UserProfileResponseDTO
     */
    message?: string;
    /**
     * HTTP 상태 코드
     * @type {number}
     * @memberof UserProfileResponseDTO
     */
    status?: number;
    /**
     * 
     * @type {UserProfileDataDTO}
     * @memberof UserProfileResponseDTO
     */
    data?: UserProfileDataDTO;
}

/**
 * Check if a given object implements the UserProfileResponseDTO interface.
 */
export function instanceOfUserProfileResponseDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfileResponseDTOFromJSON(json: any): UserProfileResponseDTO {
    return UserProfileResponseDTOFromJSONTyped(json, false);
}

export function UserProfileResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponseDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'data': !exists(json, 'data') ? undefined : UserProfileDataDTOFromJSON(json['data']),
    };
}

export function UserProfileResponseDTOToJSON(value?: UserProfileResponseDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'status': value.status,
        'data': UserProfileDataDTOToJSON(value.data),
    };
}

